apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-entry
  labels:
    app: my-entry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-entry
  template:
    metadata:
      labels:
        app: my-entry
    spec:
      containers:
      - name: my-entry
        image: indosm/entry:latest  #indosm/entry : www.aaa.com redirect image in docker hub
        ports:
        - containerPort: 80
        imagePullPolicy: Always
